#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch ~/.hushlogin

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf ~/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Add global gitignore
ln -s ~/.dotfiles/shell/.gitignore_global ~/.gitignore_global
git config --global core.excludesfile ~/.gitignore_global

# Add Laravel Homestead profile
ln -s ~/.dotfiles/shell/.homestead_profile ~/.homestead_profile

echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
